/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.AccountWithDetails;
import io.swagger.client.model.Accounts;
import org.threeten.bp.LocalDate;
import io.swagger.client.model.ResultType;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AccountInformationApi
 */
@Ignore
public class AccountInformationApiTest {

    private final AccountInformationApi api = new AccountInformationApi();

    /**
     * Get an account
     *
     * Get a specific account
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAccountTest() throws Exception {
        String authorization = null;
        String accountId = null;
        AccountWithDetails response = api.getAccount(authorization, accountId);

        // TODO: test validations
    }
    /**
     * Search for accounts
     *
     * Query all information for a set of accounts provided in the payload
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void searchForAccountsTest() throws Exception {
        String authorization = null;
        List<String> accountIds = null;
        List<LocalDate> startTime = null;
        List<LocalDate> endTime = null;
        ResultType resultType = null;
        String offset = null;
        Integer limit = null;
        Accounts response = api.searchForAccounts(authorization, accountIds, startTime, endTime, resultType, offset, limit);

        // TODO: test validations
    }
}
