/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.SuspectedFraudIncident;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for FraudNotificationApi
 */
@Ignore
public class FraudNotificationApiTest {

    private final FraudNotificationApi api = new FraudNotificationApi();

    /**
     * Notify Data Provider of fraud
     *
     * Notify Data Provider of suspected fraud
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void reportSuspectedFraudIncidentTest() throws Exception {
        String authorization = null;
        SuspectedFraudIncident body = null;
        api.reportSuspectedFraudIncident(authorization, body);

        // TODO: test validations
    }
}
