/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.AvailabilityList;
import io.swagger.client.model.Capability;
import io.swagger.client.model.CertificationMetrics;
import io.swagger.client.model.FdxVersion;
import io.swagger.client.model.OperationId;
import io.swagger.client.model.ResultType;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for MetaApi
 */
@Ignore
public class MetaApiTest {

    private final MetaApi api = new MetaApi();

    /**
     * Get API availability
     *
     * Get information about this API&#x27;s availability
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAvailabilityTest() throws Exception {
        String authorization = null;
        OperationId operationId = null;
        AvailabilityList response = api.getAvailability(authorization, operationId);

        // TODO: test validations
    }
    /**
     * Get API capability
     *
     * Get information about this API&#x27;s capability
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCapabilityTest() throws Exception {
        String authorization = null;
        OperationId operationId = null;
        FdxVersion fdxVersion = null;
        ResultType resultType = null;
        Capability response = api.getCapability(authorization, operationId, fdxVersion, resultType);

        // TODO: test validations
    }
    /**
     * Get certification performance metrics
     *
     * Get certification performance metrics for this implementer&#x27;s APIs
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCertificationMetricsTest() throws Exception {
        String authorization = null;
        OperationId operationId = null;
        CertificationMetrics response = api.getCertificationMetrics(authorization, operationId);

        // TODO: test validations
    }
}
