/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.AccountContact;
import io.swagger.client.model.Customer;
import io.swagger.client.model.Customers;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for PersonalInformationApi
 */
@Ignore
public class PersonalInformationApiTest {

    private final PersonalInformationApi api = new PersonalInformationApi();

    /**
     * Get an account&#x27;s contact information
     *
     * Get contact information on the account
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAccountContactTest() throws Exception {
        String authorization = null;
        String accountId = null;
        AccountContact response = api.getAccountContact(authorization, accountId);

        // TODO: test validations
    }
    /**
     * Customer by id
     *
     * Retrieve customer information by customer id
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCustomerTest() throws Exception {
        String authorization = null;
        String customerId = null;
        Customer response = api.getCustomer(authorization, customerId);

        // TODO: test validations
    }
    /**
     * Get current authenticated customer information
     *
     * Get information about the customer within the authorization scope
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCustomerInfoTest() throws Exception {
        String authorization = null;
        Customer response = api.getCustomerInfo(authorization);

        // TODO: test validations
    }
    /**
     * Retrieve customers
     *
     * Retrieve account holders related to consented accounts
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCustomersTest() throws Exception {
        String authorization = null;
        String offset = null;
        Integer limit = null;
        Customers response = api.getCustomers(authorization, offset, limit);

        // TODO: test validations
    }
}
