/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Indicates bill pay capabilities for an account.&lt;br/&gt; * &#x60;ACTIVE&#x60;: Can be used for bill payment&lt;br/&gt; * &#x60;AVAILABLE&#x60;: Account can be requested for bill payment&lt;br/&gt; * &#x60;NOT_AVAILABLE&#x60;: Account cannot participate in bill payment&lt;br/&gt; * &#x60;PENDING&#x60;: Account requested for bill payment, but not available yet
 */
@JsonAdapter(AccountBillPayStatus.Adapter.class)
public enum AccountBillPayStatus {
  ACTIVE("ACTIVE"),
  AVAILABLE("AVAILABLE"),
  NOT_AVAILABLE("NOT_AVAILABLE"),
  PENDING("PENDING");

  private String value;

  AccountBillPayStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AccountBillPayStatus fromValue(String input) {
    for (AccountBillPayStatus b : AccountBillPayStatus.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<AccountBillPayStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final AccountBillPayStatus enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public AccountBillPayStatus read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return AccountBillPayStatus.fromValue((String)(value));
    }
  }
}
