/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The class of an investment asset
 */
@JsonAdapter(AssetClass.Adapter.class)
public enum AssetClass {
  DOMESTICBOND("DOMESTICBOND"),
  INTLBOND("INTLBOND"),
  INTLSTOCK("INTLSTOCK"),
  LARGESTOCK("LARGESTOCK"),
  MONEYMARKET("MONEYMARKET"),
  OTHER("OTHER"),
  SMALLSTOCK("SMALLSTOCK");

  private String value;

  AssetClass(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AssetClass fromValue(String input) {
    for (AssetClass b : AssetClass.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<AssetClass> {
    @Override
    public void write(final JsonWriter jsonWriter, final AssetClass enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public AssetClass read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return AssetClass.fromValue((String)(value));
    }
  }
}
