/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.AvailabilityStatus;
import io.swagger.client.model.OperationId;
import io.swagger.client.model.PlannedAvailability;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Response object for /availability API
 */
@Schema(description = "Response object for /availability API")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-16T18:27:34.841Z[GMT]")
public class Availability {
  @SerializedName("status")
  private AvailabilityStatus status = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("operationId")
  private OperationId operationId = null;

  @SerializedName("plannedAvailability")
  private List<PlannedAvailability> plannedAvailability = null;

  public Availability status(AvailabilityStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public AvailabilityStatus getStatus() {
    return status;
  }

  public void setStatus(AvailabilityStatus status) {
    this.status = status;
  }

  public Availability description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of availability status
   * @return description
  **/
  @Schema(description = "Description of availability status")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Availability operationId(OperationId operationId) {
    this.operationId = operationId;
    return this;
  }

   /**
   * Get operationId
   * @return operationId
  **/
  @Schema(description = "")
  public OperationId getOperationId() {
    return operationId;
  }

  public void setOperationId(OperationId operationId) {
    this.operationId = operationId;
  }

  public Availability plannedAvailability(List<PlannedAvailability> plannedAvailability) {
    this.plannedAvailability = plannedAvailability;
    return this;
  }

  public Availability addPlannedAvailabilityItem(PlannedAvailability plannedAvailabilityItem) {
    if (this.plannedAvailability == null) {
      this.plannedAvailability = new ArrayList<PlannedAvailability>();
    }
    this.plannedAvailability.add(plannedAvailabilityItem);
    return this;
  }

   /**
   * Provider&#x27;s plan for API availability
   * @return plannedAvailability
  **/
  @Schema(description = "Provider's plan for API availability")
  public List<PlannedAvailability> getPlannedAvailability() {
    return plannedAvailability;
  }

  public void setPlannedAvailability(List<PlannedAvailability> plannedAvailability) {
    this.plannedAvailability = plannedAvailability;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Availability availability = (Availability) o;
    return Objects.equals(this.status, availability.status) &&
        Objects.equals(this.description, availability.description) &&
        Objects.equals(this.operationId, availability.operationId) &&
        Objects.equals(this.plannedAvailability, availability.plannedAvailability);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, description, operationId, plannedAvailability);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Availability {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    operationId: ").append(toIndentedString(operationId)).append("\n");
    sb.append("    plannedAvailability: ").append(toIndentedString(plannedAvailability)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
