/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Art associated with the card
 */
@Schema(description = "Art associated with the card")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-16T18:27:34.841Z[GMT]")
public class CardArt {
  @SerializedName("label")
  private String label = null;

  @SerializedName("imageUri")
  private String imageUri = null;

  public CardArt label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Display label for the specific image
   * @return label
  **/
  @Schema(description = "Display label for the specific image")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public CardArt imageUri(String imageUri) {
    this.imageUri = imageUri;
    return this;
  }

   /**
   * The [URI](https://datatracker.ietf.org/doc/html/rfc2397) link of a PNG, JPG or GIF image with proportions defined by [ISO 8710 ID-1](https://en.wikipedia.org/wiki/ISO/IEC_7810) with 340x210 ratio and width no greater than 512 pixels. The image at this URI must be accessible at all times, with no additional authentication headers. Typically this is an image resource located in the data provider&#x27;s public web site or Content Delivery Network
   * @return imageUri
  **/
  @Schema(description = "The [URI](https://datatracker.ietf.org/doc/html/rfc2397) link of a PNG, JPG or GIF image with proportions defined by [ISO 8710 ID-1](https://en.wikipedia.org/wiki/ISO/IEC_7810) with 340x210 ratio and width no greater than 512 pixels. The image at this URI must be accessible at all times, with no additional authentication headers. Typically this is an image resource located in the data provider's public web site or Content Delivery Network")
  public String getImageUri() {
    return imageUri;
  }

  public void setImageUri(String imageUri) {
    this.imageUri = imageUri;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardArt cardArt = (CardArt) o;
    return Objects.equals(this.label, cardArt.label) &&
        Objects.equals(this.imageUri, cardArt.imageUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(label, imageUri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardArt {\n");
    
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    imageUri: ").append(toIndentedString(imageUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
