/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Duration of the Consent Grant, per FDX UX Guidelines v1.0 (pp 18 - 20)
 */
@JsonAdapter(ConsentDurationType.Adapter.class)
public enum ConsentDurationType {
  ONE_TIME("ONE_TIME"),
  PERSISTENT("PERSISTENT"),
  TIME_BOUND("TIME_BOUND");

  private String value;

  ConsentDurationType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ConsentDurationType fromValue(String input) {
    for (ConsentDurationType b : ConsentDurationType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ConsentDurationType> {
    @Override
    public void write(final JsonWriter jsonWriter, final ConsentDurationType enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public ConsentDurationType read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return ConsentDurationType.fromValue((String)(value));
    }
  }
}
