/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ConsentResourceType;
import io.swagger.client.model.DataCluster;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Entity of permissioned resources
 */
@Schema(description = "Entity of permissioned resources")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-16T18:27:34.841Z[GMT]")
public class ConsentGrantResource {
  @SerializedName("resourceType")
  private ConsentResourceType resourceType = null;

  @SerializedName("resourceId")
  private String resourceId = null;

  @SerializedName("dataClusters")
  private List<DataCluster> dataClusters = new ArrayList<DataCluster>();

  public ConsentGrantResource resourceType(ConsentResourceType resourceType) {
    this.resourceType = resourceType;
    return this;
  }

   /**
   * Get resourceType
   * @return resourceType
  **/
  @Schema(required = true, description = "")
  public ConsentResourceType getResourceType() {
    return resourceType;
  }

  public void setResourceType(ConsentResourceType resourceType) {
    this.resourceType = resourceType;
  }

  public ConsentGrantResource resourceId(String resourceId) {
    this.resourceId = resourceId;
    return this;
  }

   /**
   * Get resourceId
   * @return resourceId
  **/
  @Schema(required = true, description = "")
  public String getResourceId() {
    return resourceId;
  }

  public void setResourceId(String resourceId) {
    this.resourceId = resourceId;
  }

  public ConsentGrantResource dataClusters(List<DataCluster> dataClusters) {
    this.dataClusters = dataClusters;
    return this;
  }

  public ConsentGrantResource addDataClustersItem(DataCluster dataClustersItem) {
    this.dataClusters.add(dataClustersItem);
    return this;
  }

   /**
   * Names of clusters of data elements permissioned
   * @return dataClusters
  **/
  @Schema(required = true, description = "Names of clusters of data elements permissioned")
  public List<DataCluster> getDataClusters() {
    return dataClusters;
  }

  public void setDataClusters(List<DataCluster> dataClusters) {
    this.dataClusters = dataClusters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsentGrantResource consentGrantResource = (ConsentGrantResource) o;
    return Objects.equals(this.resourceType, consentGrantResource.resourceType) &&
        Objects.equals(this.resourceId, consentGrantResource.resourceId) &&
        Objects.equals(this.dataClusters, consentGrantResource.dataClusters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceType, resourceId, dataClusters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsentGrantResource {\n");
    
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    resourceId: ").append(toIndentedString(resourceId)).append("\n");
    sb.append("    dataClusters: ").append(toIndentedString(dataClusters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
