/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.SecurityIdType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * Contribution information to an investment account
 */
@Schema(description = "Contribution information to an investment account")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-16T18:27:34.841Z[GMT]")
public class Contribution {
  @SerializedName("securityId")
  private String securityId = null;

  @SerializedName("securityIdType")
  private SecurityIdType securityIdType = null;

  @SerializedName("employerMatchPercentage")
  private BigDecimal employerMatchPercentage = null;

  @SerializedName("employerMatchAmount")
  private BigDecimal employerMatchAmount = null;

  @SerializedName("employeePreTaxAmount")
  private BigDecimal employeePreTaxAmount = null;

  @SerializedName("employeePreTaxPercentage")
  private BigDecimal employeePreTaxPercentage = null;

  @SerializedName("employeeAfterTaxAmount")
  private BigDecimal employeeAfterTaxAmount = null;

  @SerializedName("employeeAfterTaxPercentage")
  private BigDecimal employeeAfterTaxPercentage = null;

  @SerializedName("employeeDeferPreTaxAmount")
  private BigDecimal employeeDeferPreTaxAmount = null;

  @SerializedName("employeeDeferPreTaxPercentage")
  private BigDecimal employeeDeferPreTaxPercentage = null;

  @SerializedName("employeeYearToDate")
  private BigDecimal employeeYearToDate = null;

  @SerializedName("employerYearToDate")
  private BigDecimal employerYearToDate = null;

  @SerializedName("rolloverContributionPercentage")
  private BigDecimal rolloverContributionPercentage = null;

  @SerializedName("rolloverContributionAmount")
  private BigDecimal rolloverContributionAmount = null;

  public Contribution securityId(String securityId) {
    this.securityId = securityId;
    return this;
  }

   /**
   * Unique identifier of security
   * @return securityId
  **/
  @Schema(description = "Unique identifier of security")
  public String getSecurityId() {
    return securityId;
  }

  public void setSecurityId(String securityId) {
    this.securityId = securityId;
  }

  public Contribution securityIdType(SecurityIdType securityIdType) {
    this.securityIdType = securityIdType;
    return this;
  }

   /**
   * Get securityIdType
   * @return securityIdType
  **/
  @Schema(description = "")
  public SecurityIdType getSecurityIdType() {
    return securityIdType;
  }

  public void setSecurityIdType(SecurityIdType securityIdType) {
    this.securityIdType = securityIdType;
  }

  public Contribution employerMatchPercentage(BigDecimal employerMatchPercentage) {
    this.employerMatchPercentage = employerMatchPercentage;
    return this;
  }

   /**
   * Employer contribution match percentage
   * @return employerMatchPercentage
  **/
  @Schema(description = "Employer contribution match percentage")
  public BigDecimal getEmployerMatchPercentage() {
    return employerMatchPercentage;
  }

  public void setEmployerMatchPercentage(BigDecimal employerMatchPercentage) {
    this.employerMatchPercentage = employerMatchPercentage;
  }

  public Contribution employerMatchAmount(BigDecimal employerMatchAmount) {
    this.employerMatchAmount = employerMatchAmount;
    return this;
  }

   /**
   * Employer contribution match amount
   * @return employerMatchAmount
  **/
  @Schema(description = "Employer contribution match amount")
  public BigDecimal getEmployerMatchAmount() {
    return employerMatchAmount;
  }

  public void setEmployerMatchAmount(BigDecimal employerMatchAmount) {
    this.employerMatchAmount = employerMatchAmount;
  }

  public Contribution employeePreTaxAmount(BigDecimal employeePreTaxAmount) {
    this.employeePreTaxAmount = employeePreTaxAmount;
    return this;
  }

   /**
   * Employee pre-tax contribution amount
   * @return employeePreTaxAmount
  **/
  @Schema(description = "Employee pre-tax contribution amount")
  public BigDecimal getEmployeePreTaxAmount() {
    return employeePreTaxAmount;
  }

  public void setEmployeePreTaxAmount(BigDecimal employeePreTaxAmount) {
    this.employeePreTaxAmount = employeePreTaxAmount;
  }

  public Contribution employeePreTaxPercentage(BigDecimal employeePreTaxPercentage) {
    this.employeePreTaxPercentage = employeePreTaxPercentage;
    return this;
  }

   /**
   * Employee pre-tax contribution percentage
   * @return employeePreTaxPercentage
  **/
  @Schema(description = "Employee pre-tax contribution percentage")
  public BigDecimal getEmployeePreTaxPercentage() {
    return employeePreTaxPercentage;
  }

  public void setEmployeePreTaxPercentage(BigDecimal employeePreTaxPercentage) {
    this.employeePreTaxPercentage = employeePreTaxPercentage;
  }

  public Contribution employeeAfterTaxAmount(BigDecimal employeeAfterTaxAmount) {
    this.employeeAfterTaxAmount = employeeAfterTaxAmount;
    return this;
  }

   /**
   * Employee after tax contribution amount
   * @return employeeAfterTaxAmount
  **/
  @Schema(description = "Employee after tax contribution amount")
  public BigDecimal getEmployeeAfterTaxAmount() {
    return employeeAfterTaxAmount;
  }

  public void setEmployeeAfterTaxAmount(BigDecimal employeeAfterTaxAmount) {
    this.employeeAfterTaxAmount = employeeAfterTaxAmount;
  }

  public Contribution employeeAfterTaxPercentage(BigDecimal employeeAfterTaxPercentage) {
    this.employeeAfterTaxPercentage = employeeAfterTaxPercentage;
    return this;
  }

   /**
   * Employee after tax contribution percentage
   * @return employeeAfterTaxPercentage
  **/
  @Schema(description = "Employee after tax contribution percentage")
  public BigDecimal getEmployeeAfterTaxPercentage() {
    return employeeAfterTaxPercentage;
  }

  public void setEmployeeAfterTaxPercentage(BigDecimal employeeAfterTaxPercentage) {
    this.employeeAfterTaxPercentage = employeeAfterTaxPercentage;
  }

  public Contribution employeeDeferPreTaxAmount(BigDecimal employeeDeferPreTaxAmount) {
    this.employeeDeferPreTaxAmount = employeeDeferPreTaxAmount;
    return this;
  }

   /**
   * Employee defer pre-tax contribution match amount
   * @return employeeDeferPreTaxAmount
  **/
  @Schema(description = "Employee defer pre-tax contribution match amount")
  public BigDecimal getEmployeeDeferPreTaxAmount() {
    return employeeDeferPreTaxAmount;
  }

  public void setEmployeeDeferPreTaxAmount(BigDecimal employeeDeferPreTaxAmount) {
    this.employeeDeferPreTaxAmount = employeeDeferPreTaxAmount;
  }

  public Contribution employeeDeferPreTaxPercentage(BigDecimal employeeDeferPreTaxPercentage) {
    this.employeeDeferPreTaxPercentage = employeeDeferPreTaxPercentage;
    return this;
  }

   /**
   * Employee defer pre-tax contribution match percentage
   * @return employeeDeferPreTaxPercentage
  **/
  @Schema(description = "Employee defer pre-tax contribution match percentage")
  public BigDecimal getEmployeeDeferPreTaxPercentage() {
    return employeeDeferPreTaxPercentage;
  }

  public void setEmployeeDeferPreTaxPercentage(BigDecimal employeeDeferPreTaxPercentage) {
    this.employeeDeferPreTaxPercentage = employeeDeferPreTaxPercentage;
  }

  public Contribution employeeYearToDate(BigDecimal employeeYearToDate) {
    this.employeeYearToDate = employeeYearToDate;
    return this;
  }

   /**
   * Employee total year to date contribution
   * @return employeeYearToDate
  **/
  @Schema(description = "Employee total year to date contribution")
  public BigDecimal getEmployeeYearToDate() {
    return employeeYearToDate;
  }

  public void setEmployeeYearToDate(BigDecimal employeeYearToDate) {
    this.employeeYearToDate = employeeYearToDate;
  }

  public Contribution employerYearToDate(BigDecimal employerYearToDate) {
    this.employerYearToDate = employerYearToDate;
    return this;
  }

   /**
   * Employer total year to date contribution
   * @return employerYearToDate
  **/
  @Schema(description = "Employer total year to date contribution")
  public BigDecimal getEmployerYearToDate() {
    return employerYearToDate;
  }

  public void setEmployerYearToDate(BigDecimal employerYearToDate) {
    this.employerYearToDate = employerYearToDate;
  }

  public Contribution rolloverContributionPercentage(BigDecimal rolloverContributionPercentage) {
    this.rolloverContributionPercentage = rolloverContributionPercentage;
    return this;
  }

   /**
   * Rollover contribution percentage
   * @return rolloverContributionPercentage
  **/
  @Schema(description = "Rollover contribution percentage")
  public BigDecimal getRolloverContributionPercentage() {
    return rolloverContributionPercentage;
  }

  public void setRolloverContributionPercentage(BigDecimal rolloverContributionPercentage) {
    this.rolloverContributionPercentage = rolloverContributionPercentage;
  }

  public Contribution rolloverContributionAmount(BigDecimal rolloverContributionAmount) {
    this.rolloverContributionAmount = rolloverContributionAmount;
    return this;
  }

   /**
   * Rollover contribution Amount
   * @return rolloverContributionAmount
  **/
  @Schema(description = "Rollover contribution Amount")
  public BigDecimal getRolloverContributionAmount() {
    return rolloverContributionAmount;
  }

  public void setRolloverContributionAmount(BigDecimal rolloverContributionAmount) {
    this.rolloverContributionAmount = rolloverContributionAmount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Contribution contribution = (Contribution) o;
    return Objects.equals(this.securityId, contribution.securityId) &&
        Objects.equals(this.securityIdType, contribution.securityIdType) &&
        Objects.equals(this.employerMatchPercentage, contribution.employerMatchPercentage) &&
        Objects.equals(this.employerMatchAmount, contribution.employerMatchAmount) &&
        Objects.equals(this.employeePreTaxAmount, contribution.employeePreTaxAmount) &&
        Objects.equals(this.employeePreTaxPercentage, contribution.employeePreTaxPercentage) &&
        Objects.equals(this.employeeAfterTaxAmount, contribution.employeeAfterTaxAmount) &&
        Objects.equals(this.employeeAfterTaxPercentage, contribution.employeeAfterTaxPercentage) &&
        Objects.equals(this.employeeDeferPreTaxAmount, contribution.employeeDeferPreTaxAmount) &&
        Objects.equals(this.employeeDeferPreTaxPercentage, contribution.employeeDeferPreTaxPercentage) &&
        Objects.equals(this.employeeYearToDate, contribution.employeeYearToDate) &&
        Objects.equals(this.employerYearToDate, contribution.employerYearToDate) &&
        Objects.equals(this.rolloverContributionPercentage, contribution.rolloverContributionPercentage) &&
        Objects.equals(this.rolloverContributionAmount, contribution.rolloverContributionAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(securityId, securityIdType, employerMatchPercentage, employerMatchAmount, employeePreTaxAmount, employeePreTaxPercentage, employeeAfterTaxAmount, employeeAfterTaxPercentage, employeeDeferPreTaxAmount, employeeDeferPreTaxPercentage, employeeYearToDate, employerYearToDate, rolloverContributionPercentage, rolloverContributionAmount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Contribution {\n");
    
    sb.append("    securityId: ").append(toIndentedString(securityId)).append("\n");
    sb.append("    securityIdType: ").append(toIndentedString(securityIdType)).append("\n");
    sb.append("    employerMatchPercentage: ").append(toIndentedString(employerMatchPercentage)).append("\n");
    sb.append("    employerMatchAmount: ").append(toIndentedString(employerMatchAmount)).append("\n");
    sb.append("    employeePreTaxAmount: ").append(toIndentedString(employeePreTaxAmount)).append("\n");
    sb.append("    employeePreTaxPercentage: ").append(toIndentedString(employeePreTaxPercentage)).append("\n");
    sb.append("    employeeAfterTaxAmount: ").append(toIndentedString(employeeAfterTaxAmount)).append("\n");
    sb.append("    employeeAfterTaxPercentage: ").append(toIndentedString(employeeAfterTaxPercentage)).append("\n");
    sb.append("    employeeDeferPreTaxAmount: ").append(toIndentedString(employeeDeferPreTaxAmount)).append("\n");
    sb.append("    employeeDeferPreTaxPercentage: ").append(toIndentedString(employeeDeferPreTaxPercentage)).append("\n");
    sb.append("    employeeYearToDate: ").append(toIndentedString(employeeYearToDate)).append("\n");
    sb.append("    employerYearToDate: ").append(toIndentedString(employerYearToDate)).append("\n");
    sb.append("    rolloverContributionPercentage: ").append(toIndentedString(rolloverContributionPercentage)).append("\n");
    sb.append("    rolloverContributionAmount: ").append(toIndentedString(rolloverContributionAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
