/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.CallType;
import io.swagger.client.model.CouponMatureFrequency;
import io.swagger.client.model.DebtClass;
import io.swagger.client.model.DebtType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import org.threeten.bp.LocalDate;
/**
 * An investment in a debt security
 */
@Schema(description = "An investment in a debt security")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-16T18:27:34.841Z[GMT]")
public class DebtSecurity {
  @SerializedName("parValue")
  private BigDecimal parValue = null;

  @SerializedName("debtType")
  private DebtType debtType = null;

  @SerializedName("debtClass")
  private DebtClass debtClass = null;

  @SerializedName("couponRate")
  private BigDecimal couponRate = null;

  @SerializedName("couponDate")
  private LocalDate couponDate = null;

  @SerializedName("couponMatureFrequency")
  private CouponMatureFrequency couponMatureFrequency = null;

  @SerializedName("callPrice")
  private BigDecimal callPrice = null;

  @SerializedName("yieldToCall")
  private BigDecimal yieldToCall = null;

  @SerializedName("callDate")
  private LocalDate callDate = null;

  @SerializedName("callType")
  private CallType callType = null;

  @SerializedName("yieldToMaturity")
  private BigDecimal yieldToMaturity = null;

  @SerializedName("bondMaturityDate")
  private LocalDate bondMaturityDate = null;

  public DebtSecurity parValue(BigDecimal parValue) {
    this.parValue = parValue;
    return this;
  }

   /**
   * Par value amount
   * @return parValue
  **/
  @Schema(description = "Par value amount")
  public BigDecimal getParValue() {
    return parValue;
  }

  public void setParValue(BigDecimal parValue) {
    this.parValue = parValue;
  }

  public DebtSecurity debtType(DebtType debtType) {
    this.debtType = debtType;
    return this;
  }

   /**
   * Get debtType
   * @return debtType
  **/
  @Schema(description = "")
  public DebtType getDebtType() {
    return debtType;
  }

  public void setDebtType(DebtType debtType) {
    this.debtType = debtType;
  }

  public DebtSecurity debtClass(DebtClass debtClass) {
    this.debtClass = debtClass;
    return this;
  }

   /**
   * Get debtClass
   * @return debtClass
  **/
  @Schema(description = "")
  public DebtClass getDebtClass() {
    return debtClass;
  }

  public void setDebtClass(DebtClass debtClass) {
    this.debtClass = debtClass;
  }

  public DebtSecurity couponRate(BigDecimal couponRate) {
    this.couponRate = couponRate;
    return this;
  }

   /**
   * Bond coupon rate for next closest call date
   * @return couponRate
  **/
  @Schema(description = "Bond coupon rate for next closest call date")
  public BigDecimal getCouponRate() {
    return couponRate;
  }

  public void setCouponRate(BigDecimal couponRate) {
    this.couponRate = couponRate;
  }

  public DebtSecurity couponDate(LocalDate couponDate) {
    this.couponDate = couponDate;
    return this;
  }

   /**
   * Get couponDate
   * @return couponDate
  **/
  @Schema(description = "")
  public LocalDate getCouponDate() {
    return couponDate;
  }

  public void setCouponDate(LocalDate couponDate) {
    this.couponDate = couponDate;
  }

  public DebtSecurity couponMatureFrequency(CouponMatureFrequency couponMatureFrequency) {
    this.couponMatureFrequency = couponMatureFrequency;
    return this;
  }

   /**
   * Get couponMatureFrequency
   * @return couponMatureFrequency
  **/
  @Schema(description = "")
  public CouponMatureFrequency getCouponMatureFrequency() {
    return couponMatureFrequency;
  }

  public void setCouponMatureFrequency(CouponMatureFrequency couponMatureFrequency) {
    this.couponMatureFrequency = couponMatureFrequency;
  }

  public DebtSecurity callPrice(BigDecimal callPrice) {
    this.callPrice = callPrice;
    return this;
  }

   /**
   * Bond call price
   * @return callPrice
  **/
  @Schema(description = "Bond call price")
  public BigDecimal getCallPrice() {
    return callPrice;
  }

  public void setCallPrice(BigDecimal callPrice) {
    this.callPrice = callPrice;
  }

  public DebtSecurity yieldToCall(BigDecimal yieldToCall) {
    this.yieldToCall = yieldToCall;
    return this;
  }

   /**
   * Yield to next call
   * @return yieldToCall
  **/
  @Schema(description = "Yield to next call")
  public BigDecimal getYieldToCall() {
    return yieldToCall;
  }

  public void setYieldToCall(BigDecimal yieldToCall) {
    this.yieldToCall = yieldToCall;
  }

  public DebtSecurity callDate(LocalDate callDate) {
    this.callDate = callDate;
    return this;
  }

   /**
   * Get callDate
   * @return callDate
  **/
  @Schema(description = "")
  public LocalDate getCallDate() {
    return callDate;
  }

  public void setCallDate(LocalDate callDate) {
    this.callDate = callDate;
  }

  public DebtSecurity callType(CallType callType) {
    this.callType = callType;
    return this;
  }

   /**
   * Get callType
   * @return callType
  **/
  @Schema(description = "")
  public CallType getCallType() {
    return callType;
  }

  public void setCallType(CallType callType) {
    this.callType = callType;
  }

  public DebtSecurity yieldToMaturity(BigDecimal yieldToMaturity) {
    this.yieldToMaturity = yieldToMaturity;
    return this;
  }

   /**
   * Yield to maturity
   * @return yieldToMaturity
  **/
  @Schema(description = "Yield to maturity")
  public BigDecimal getYieldToMaturity() {
    return yieldToMaturity;
  }

  public void setYieldToMaturity(BigDecimal yieldToMaturity) {
    this.yieldToMaturity = yieldToMaturity;
  }

  public DebtSecurity bondMaturityDate(LocalDate bondMaturityDate) {
    this.bondMaturityDate = bondMaturityDate;
    return this;
  }

   /**
   * Get bondMaturityDate
   * @return bondMaturityDate
  **/
  @Schema(description = "")
  public LocalDate getBondMaturityDate() {
    return bondMaturityDate;
  }

  public void setBondMaturityDate(LocalDate bondMaturityDate) {
    this.bondMaturityDate = bondMaturityDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DebtSecurity debtSecurity = (DebtSecurity) o;
    return Objects.equals(this.parValue, debtSecurity.parValue) &&
        Objects.equals(this.debtType, debtSecurity.debtType) &&
        Objects.equals(this.debtClass, debtSecurity.debtClass) &&
        Objects.equals(this.couponRate, debtSecurity.couponRate) &&
        Objects.equals(this.couponDate, debtSecurity.couponDate) &&
        Objects.equals(this.couponMatureFrequency, debtSecurity.couponMatureFrequency) &&
        Objects.equals(this.callPrice, debtSecurity.callPrice) &&
        Objects.equals(this.yieldToCall, debtSecurity.yieldToCall) &&
        Objects.equals(this.callDate, debtSecurity.callDate) &&
        Objects.equals(this.callType, debtSecurity.callType) &&
        Objects.equals(this.yieldToMaturity, debtSecurity.yieldToMaturity) &&
        Objects.equals(this.bondMaturityDate, debtSecurity.bondMaturityDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parValue, debtType, debtClass, couponRate, couponDate, couponMatureFrequency, callPrice, yieldToCall, callDate, callType, yieldToMaturity, bondMaturityDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DebtSecurity {\n");
    
    sb.append("    parValue: ").append(toIndentedString(parValue)).append("\n");
    sb.append("    debtType: ").append(toIndentedString(debtType)).append("\n");
    sb.append("    debtClass: ").append(toIndentedString(debtClass)).append("\n");
    sb.append("    couponRate: ").append(toIndentedString(couponRate)).append("\n");
    sb.append("    couponDate: ").append(toIndentedString(couponDate)).append("\n");
    sb.append("    couponMatureFrequency: ").append(toIndentedString(couponMatureFrequency)).append("\n");
    sb.append("    callPrice: ").append(toIndentedString(callPrice)).append("\n");
    sb.append("    yieldToCall: ").append(toIndentedString(yieldToCall)).append("\n");
    sb.append("    callDate: ").append(toIndentedString(callDate)).append("\n");
    sb.append("    callType: ").append(toIndentedString(callType)).append("\n");
    sb.append("    yieldToMaturity: ").append(toIndentedString(yieldToMaturity)).append("\n");
    sb.append("    bondMaturityDate: ").append(toIndentedString(bondMaturityDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
