/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The list of prior and current FDX major and minor versions.
 */
@JsonAdapter(FdxVersion.Adapter.class)
public enum FdxVersion {
  V1_0("V1.0"),
  V2_0("V2.0"),
  V2_1("V2.1"),
  V3_0("V3.0"),
  V4_0("V4.0"),
  V4_1("V4.1"),
  V4_2("V4.2"),
  V4_5("V4.5"),
  V4_6("V4.6"),
  V5_0("V5.0");

  private String value;

  FdxVersion(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static FdxVersion fromValue(String input) {
    for (FdxVersion b : FdxVersion.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<FdxVersion> {
    @Override
    public void write(final JsonWriter jsonWriter, final FdxVersion enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public FdxVersion read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return FdxVersion.fromValue((String)(value));
    }
  }
}
