/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Currency;
import io.swagger.client.model.InvestmentBalanceType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import org.threeten.bp.LocalDate;
/**
 * A point-in-time balance of the investment account
 */
@Schema(description = "A point-in-time balance of the investment account")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-16T18:27:34.841Z[GMT]")
public class InvestmentBalance {
  @SerializedName("balanceName")
  private String balanceName = null;

  @SerializedName("balanceDescription")
  private String balanceDescription = null;

  @SerializedName("balanceType")
  private InvestmentBalanceType balanceType = null;

  @SerializedName("balanceValue")
  private BigDecimal balanceValue = null;

  @SerializedName("balanceDate")
  private LocalDate balanceDate = null;

  @SerializedName("currency")
  private Currency currency = null;

  public InvestmentBalance balanceName(String balanceName) {
    this.balanceName = balanceName;
    return this;
  }

   /**
   * Name of the balance
   * @return balanceName
  **/
  @Schema(description = "Name of the balance")
  public String getBalanceName() {
    return balanceName;
  }

  public void setBalanceName(String balanceName) {
    this.balanceName = balanceName;
  }

  public InvestmentBalance balanceDescription(String balanceDescription) {
    this.balanceDescription = balanceDescription;
    return this;
  }

   /**
   * Description of balance
   * @return balanceDescription
  **/
  @Schema(description = "Description of balance")
  public String getBalanceDescription() {
    return balanceDescription;
  }

  public void setBalanceDescription(String balanceDescription) {
    this.balanceDescription = balanceDescription;
  }

  public InvestmentBalance balanceType(InvestmentBalanceType balanceType) {
    this.balanceType = balanceType;
    return this;
  }

   /**
   * Get balanceType
   * @return balanceType
  **/
  @Schema(description = "")
  public InvestmentBalanceType getBalanceType() {
    return balanceType;
  }

  public void setBalanceType(InvestmentBalanceType balanceType) {
    this.balanceType = balanceType;
  }

  public InvestmentBalance balanceValue(BigDecimal balanceValue) {
    this.balanceValue = balanceValue;
    return this;
  }

   /**
   * Value of named balance
   * @return balanceValue
  **/
  @Schema(description = "Value of named balance")
  public BigDecimal getBalanceValue() {
    return balanceValue;
  }

  public void setBalanceValue(BigDecimal balanceValue) {
    this.balanceValue = balanceValue;
  }

  public InvestmentBalance balanceDate(LocalDate balanceDate) {
    this.balanceDate = balanceDate;
    return this;
  }

   /**
   * Get balanceDate
   * @return balanceDate
  **/
  @Schema(description = "")
  public LocalDate getBalanceDate() {
    return balanceDate;
  }

  public void setBalanceDate(LocalDate balanceDate) {
    this.balanceDate = balanceDate;
  }

  public InvestmentBalance currency(Currency currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @Schema(description = "")
  public Currency getCurrency() {
    return currency;
  }

  public void setCurrency(Currency currency) {
    this.currency = currency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvestmentBalance investmentBalance = (InvestmentBalance) o;
    return Objects.equals(this.balanceName, investmentBalance.balanceName) &&
        Objects.equals(this.balanceDescription, investmentBalance.balanceDescription) &&
        Objects.equals(this.balanceType, investmentBalance.balanceType) &&
        Objects.equals(this.balanceValue, investmentBalance.balanceValue) &&
        Objects.equals(this.balanceDate, investmentBalance.balanceDate) &&
        Objects.equals(this.currency, investmentBalance.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(balanceName, balanceDescription, balanceType, balanceValue, balanceDate, currency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvestmentBalance {\n");
    
    sb.append("    balanceName: ").append(toIndentedString(balanceName)).append("\n");
    sb.append("    balanceDescription: ").append(toIndentedString(balanceDescription)).append("\n");
    sb.append("    balanceType: ").append(toIndentedString(balanceType)).append("\n");
    sb.append("    balanceValue: ").append(toIndentedString(balanceValue)).append("\n");
    sb.append("    balanceDate: ").append(toIndentedString(balanceDate)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
