/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * ISO 4217 Currency codes
 */
@JsonAdapter(Iso4217Code.Adapter.class)
public enum Iso4217Code {
  AED("AED"),
  AFN("AFN"),
  ALL("ALL"),
  AMD("AMD"),
  ANG("ANG"),
  AOA("AOA"),
  ARS("ARS"),
  AUD("AUD"),
  AWG("AWG"),
  AZN("AZN"),
  BAM("BAM"),
  BBD("BBD"),
  BDT("BDT"),
  BGN("BGN"),
  BHD("BHD"),
  BIF("BIF"),
  BMD("BMD"),
  BND("BND"),
  BOB("BOB"),
  BOV("BOV"),
  BRL("BRL"),
  BSD("BSD"),
  BTN("BTN"),
  BWP("BWP"),
  BYR("BYR"),
  BZD("BZD"),
  CAD("CAD"),
  CDF("CDF"),
  CHE("CHE"),
  CHF("CHF"),
  CHW("CHW"),
  CLF("CLF"),
  CLP("CLP"),
  CNY("CNY"),
  COP("COP"),
  COU("COU"),
  CRC("CRC"),
  CUC("CUC"),
  CUP("CUP"),
  CVE("CVE"),
  CZK("CZK"),
  DJF("DJF"),
  DKK("DKK"),
  DOP("DOP"),
  DZD("DZD"),
  EGP("EGP"),
  ERN("ERN"),
  ETB("ETB"),
  EUR("EUR"),
  FJD("FJD"),
  FKP("FKP"),
  GBP("GBP"),
  GEL("GEL"),
  GHS("GHS"),
  GIP("GIP"),
  GMD("GMD"),
  GNF("GNF"),
  GTQ("GTQ"),
  GYD("GYD"),
  HKD("HKD"),
  HNL("HNL"),
  HRK("HRK"),
  HTG("HTG"),
  HUF("HUF"),
  IDR("IDR"),
  ILS("ILS"),
  INR("INR"),
  IQD("IQD"),
  IRR("IRR"),
  ISK("ISK"),
  JMD("JMD"),
  JOD("JOD"),
  JPY("JPY"),
  KES("KES"),
  KGS("KGS"),
  KHR("KHR"),
  KMF("KMF"),
  KPW("KPW"),
  KRW("KRW"),
  KWD("KWD"),
  KYD("KYD"),
  KZT("KZT"),
  LAK("LAK"),
  LBP("LBP"),
  LKR("LKR"),
  LRD("LRD"),
  LSL("LSL"),
  LYD("LYD"),
  MAD("MAD"),
  MDL("MDL"),
  MGA("MGA"),
  MKD("MKD"),
  MMK("MMK"),
  MNT("MNT"),
  MOP("MOP"),
  MRO("MRO"),
  MUR("MUR"),
  MVR("MVR"),
  MWK("MWK"),
  MXN("MXN"),
  MXV("MXV"),
  MYR("MYR"),
  MZN("MZN"),
  NAD("NAD"),
  NGN("NGN"),
  NIO("NIO"),
  NOK("NOK"),
  NPR("NPR"),
  NZD("NZD"),
  OMR("OMR"),
  PAB("PAB"),
  PEN("PEN"),
  PGK("PGK"),
  PHP("PHP"),
  PKR("PKR"),
  PLN("PLN"),
  PYG("PYG"),
  QAR("QAR"),
  RON("RON"),
  RSD("RSD"),
  RUB("RUB"),
  RWF("RWF"),
  SAR("SAR"),
  SBD("SBD"),
  SCR("SCR"),
  SDG("SDG"),
  SEK("SEK"),
  SGD("SGD"),
  SHP("SHP"),
  SLL("SLL"),
  SOS("SOS"),
  SRD("SRD"),
  SSP("SSP"),
  STD("STD"),
  SVC("SVC"),
  SYP("SYP"),
  SZL("SZL"),
  THB("THB"),
  TJS("TJS"),
  TMT("TMT"),
  TND("TND"),
  TOP("TOP"),
  TRY("TRY"),
  TTD("TTD"),
  TWD("TWD"),
  TZS("TZS"),
  UAH("UAH"),
  UGX("UGX"),
  USD("USD"),
  USN("USN"),
  UYI("UYI"),
  UYU("UYU"),
  UZS("UZS"),
  VEF("VEF"),
  VND("VND"),
  VUV("VUV"),
  WST("WST"),
  XAF("XAF"),
  XAG("XAG"),
  XAU("XAU"),
  XBA("XBA"),
  XBB("XBB"),
  XBC("XBC"),
  XBD("XBD"),
  XCD("XCD"),
  XDR("XDR"),
  XOF("XOF"),
  XPD("XPD"),
  XPF("XPF"),
  XPT("XPT"),
  XSU("XSU"),
  XTS("XTS"),
  XUA("XUA"),
  XXX("XXX"),
  YER("YER"),
  ZAR("ZAR"),
  ZMW("ZMW"),
  ZWL("ZWL");

  private String value;

  Iso4217Code(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Iso4217Code fromValue(String input) {
    for (Iso4217Code b : Iso4217Code.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<Iso4217Code> {
    @Override
    public void write(final JsonWriter jsonWriter, final Iso4217Code enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public Iso4217Code read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return Iso4217Code.fromValue((String)(value));
    }
  }
}
