/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.MutualFundType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import org.threeten.bp.LocalDate;
/**
 * A mutual fund
 */
@Schema(description = "A mutual fund")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-16T18:27:34.841Z[GMT]")
public class MutualFundSecurity {
  @SerializedName("mutualFundType")
  private MutualFundType mutualFundType = null;

  @SerializedName("unitsStreet")
  private BigDecimal unitsStreet = null;

  @SerializedName("unitsUser")
  private BigDecimal unitsUser = null;

  @SerializedName("reinvestDividends")
  private Boolean reinvestDividends = null;

  @SerializedName("reinvestCapitalGains")
  private Boolean reinvestCapitalGains = null;

  @SerializedName("yield")
  private BigDecimal yield = null;

  @SerializedName("yieldAsOfDate")
  private LocalDate yieldAsOfDate = null;

  public MutualFundSecurity mutualFundType(MutualFundType mutualFundType) {
    this.mutualFundType = mutualFundType;
    return this;
  }

   /**
   * Get mutualFundType
   * @return mutualFundType
  **/
  @Schema(description = "")
  public MutualFundType getMutualFundType() {
    return mutualFundType;
  }

  public void setMutualFundType(MutualFundType mutualFundType) {
    this.mutualFundType = mutualFundType;
  }

  public MutualFundSecurity unitsStreet(BigDecimal unitsStreet) {
    this.unitsStreet = unitsStreet;
    return this;
  }

   /**
   * Units in the FI&#x27;s street name, positive quantity
   * @return unitsStreet
  **/
  @Schema(description = "Units in the FI's street name, positive quantity")
  public BigDecimal getUnitsStreet() {
    return unitsStreet;
  }

  public void setUnitsStreet(BigDecimal unitsStreet) {
    this.unitsStreet = unitsStreet;
  }

  public MutualFundSecurity unitsUser(BigDecimal unitsUser) {
    this.unitsUser = unitsUser;
    return this;
  }

   /**
   * Units in user&#x27;s name directly, positive  quantity
   * @return unitsUser
  **/
  @Schema(description = "Units in user's name directly, positive  quantity")
  public BigDecimal getUnitsUser() {
    return unitsUser;
  }

  public void setUnitsUser(BigDecimal unitsUser) {
    this.unitsUser = unitsUser;
  }

  public MutualFundSecurity reinvestDividends(Boolean reinvestDividends) {
    this.reinvestDividends = reinvestDividends;
    return this;
  }

   /**
   * Reinvest dividends
   * @return reinvestDividends
  **/
  @Schema(description = "Reinvest dividends")
  public Boolean isReinvestDividends() {
    return reinvestDividends;
  }

  public void setReinvestDividends(Boolean reinvestDividends) {
    this.reinvestDividends = reinvestDividends;
  }

  public MutualFundSecurity reinvestCapitalGains(Boolean reinvestCapitalGains) {
    this.reinvestCapitalGains = reinvestCapitalGains;
    return this;
  }

   /**
   * Reinvest capital gains
   * @return reinvestCapitalGains
  **/
  @Schema(description = "Reinvest capital gains")
  public Boolean isReinvestCapitalGains() {
    return reinvestCapitalGains;
  }

  public void setReinvestCapitalGains(Boolean reinvestCapitalGains) {
    this.reinvestCapitalGains = reinvestCapitalGains;
  }

  public MutualFundSecurity yield(BigDecimal yield) {
    this.yield = yield;
    return this;
  }

   /**
   * Current yield reported as portion of the fund&#x27;s assets
   * @return yield
  **/
  @Schema(description = "Current yield reported as portion of the fund's assets")
  public BigDecimal getYield() {
    return yield;
  }

  public void setYield(BigDecimal yield) {
    this.yield = yield;
  }

  public MutualFundSecurity yieldAsOfDate(LocalDate yieldAsOfDate) {
    this.yieldAsOfDate = yieldAsOfDate;
    return this;
  }

   /**
   * Get yieldAsOfDate
   * @return yieldAsOfDate
  **/
  @Schema(description = "")
  public LocalDate getYieldAsOfDate() {
    return yieldAsOfDate;
  }

  public void setYieldAsOfDate(LocalDate yieldAsOfDate) {
    this.yieldAsOfDate = yieldAsOfDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MutualFundSecurity mutualFundSecurity = (MutualFundSecurity) o;
    return Objects.equals(this.mutualFundType, mutualFundSecurity.mutualFundType) &&
        Objects.equals(this.unitsStreet, mutualFundSecurity.unitsStreet) &&
        Objects.equals(this.unitsUser, mutualFundSecurity.unitsUser) &&
        Objects.equals(this.reinvestDividends, mutualFundSecurity.reinvestDividends) &&
        Objects.equals(this.reinvestCapitalGains, mutualFundSecurity.reinvestCapitalGains) &&
        Objects.equals(this.yield, mutualFundSecurity.yield) &&
        Objects.equals(this.yieldAsOfDate, mutualFundSecurity.yieldAsOfDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mutualFundType, unitsStreet, unitsUser, reinvestDividends, reinvestCapitalGains, yield, yieldAsOfDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MutualFundSecurity {\n");
    
    sb.append("    mutualFundType: ").append(toIndentedString(mutualFundType)).append("\n");
    sb.append("    unitsStreet: ").append(toIndentedString(unitsStreet)).append("\n");
    sb.append("    unitsUser: ").append(toIndentedString(unitsUser)).append("\n");
    sb.append("    reinvestDividends: ").append(toIndentedString(reinvestDividends)).append("\n");
    sb.append("    reinvestCapitalGains: ").append(toIndentedString(reinvestCapitalGains)).append("\n");
    sb.append("    yield: ").append(toIndentedString(yield)).append("\n");
    sb.append("    yieldAsOfDate: ").append(toIndentedString(yieldAsOfDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
