/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.HateoasLink;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Resource URLs for retrieving next or previous datasets
 */
@Schema(description = "Resource URLs for retrieving next or previous datasets")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-16T18:27:34.841Z[GMT]")
public class PageMetadataLinks {
  @SerializedName("next")
  private HateoasLink next = null;

  @SerializedName("prev")
  private HateoasLink prev = null;

  public PageMetadataLinks next(HateoasLink next) {
    this.next = next;
    return this;
  }

   /**
   * Get next
   * @return next
  **/
  @Schema(description = "")
  public HateoasLink getNext() {
    return next;
  }

  public void setNext(HateoasLink next) {
    this.next = next;
  }

  public PageMetadataLinks prev(HateoasLink prev) {
    this.prev = prev;
    return this;
  }

   /**
   * Get prev
   * @return prev
  **/
  @Schema(description = "")
  public HateoasLink getPrev() {
    return prev;
  }

  public void setPrev(HateoasLink prev) {
    this.prev = prev;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageMetadataLinks pageMetadataLinks = (PageMetadataLinks) o;
    return Objects.equals(this.next, pageMetadataLinks.next) &&
        Objects.equals(this.prev, pageMetadataLinks.prev);
  }

  @Override
  public int hashCode() {
    return Objects.hash(next, prev);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PageMetadataLinks {\n");
    
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    prev: ").append(toIndentedString(prev)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
