/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Frequency of annuity payments.&lt;br/&gt; &lt;br/&gt; | Value | Description |&lt;br/&gt; |-----|-----|&lt;br/&gt; | ANNUALLY | Paid Annually |&lt;br/&gt; | BIWEEKLY | Paid Bi-weekly |&lt;br/&gt; | DAILY | Paid Daily |&lt;br/&gt; | MONTHLY | Paid Monthly |&lt;br/&gt; | SEMIANNUALLY | Paid Semi-annually |&lt;br/&gt; | SEMIMONTHLY | Paid Semi-monthly |
 */
@JsonAdapter(PayoutMode.Adapter.class)
public enum PayoutMode {
  ANNUALLY("ANNUALLY"),
  BIWEEKLY("BIWEEKLY"),
  DAILY("DAILY"),
  MONTHLY("MONTHLY"),
  SEMIANNUALLY("SEMIANNUALLY"),
  SEMIMONTHLY("SEMIMONTHLY"),
  WEEKLY("WEEKLY");

  private String value;

  PayoutMode(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PayoutMode fromValue(String input) {
    for (PayoutMode b : PayoutMode.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<PayoutMode> {
    @Override
    public void write(final JsonWriter jsonWriter, final PayoutMode enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public PayoutMode read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return PayoutMode.fromValue((String)(value));
    }
  }
}
