/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Distinguishes options in annuity payouts; values are defined by the carrier.&lt;br/&gt; &lt;br/&gt; |Value | Description |&lt;br/&gt; |-----|-----|&lt;br/&gt; | FIXED | Payout is based on a guaranteed rate of return by the carrier |&lt;br/&gt; | VARIABLE | Payout is based on the variable performance of the investments the buyer chooses |
 */
@JsonAdapter(PolicyProductType.Adapter.class)
public enum PolicyProductType {
  FIXED("FIXED"),
  VARIABLE("VARIABLE");

  private String value;

  PolicyProductType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PolicyProductType fromValue(String input) {
    for (PolicyProductType b : PolicyProductType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<PolicyProductType> {
    @Override
    public void write(final JsonWriter jsonWriter, final PolicyProductType enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public PolicyProductType read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return PolicyProductType.fromValue((String)(value));
    }
  }
}
