/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The type of the reward balance.  Example: a reward program awarding \&quot;Stars\&quot; for purchases would use the &#x60;POINTS&#x60; reward type.&lt;br/&gt; * &#x60;CASHBACK&#x60;: Rewards balances enumerated using a monetary amount&lt;br/&gt; * &#x60;MILES&#x60;: Rewards balances enumerated using distance&lt;br/&gt; * &#x60;POINTS&#x60;: Default when a reward balance is not of type CASHBACK or MILES 
 */
@JsonAdapter(RewardType.Adapter.class)
public enum RewardType {
  CASHBACK("CASHBACK"),
  MILES("MILES"),
  POINTS("POINTS");

  private String value;

  RewardType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static RewardType fromValue(String input) {
    for (RewardType b : RewardType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<RewardType> {
    @Override
    public void write(final JsonWriter jsonWriter, final RewardType enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public RewardType read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return RewardType.fromValue((String)(value));
    }
  }
}
