/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.BusinessOrConsumer;
import io.swagger.client.model.RewardBalance;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Details of a single membership in a reward programs
 */
@Schema(description = "Details of a single membership in a reward programs")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-16T18:27:34.841Z[GMT]")
public class RewardMembership {
  @SerializedName("accountIds")
  private List<String> accountIds = null;

  @SerializedName("customerId")
  private String customerId = null;

  @SerializedName("memberId")
  private String memberId = null;

  @SerializedName("memberNumber")
  private String memberNumber = null;

  @SerializedName("memberTier")
  private String memberTier = null;

  @SerializedName("businessOrConsumer")
  private BusinessOrConsumer businessOrConsumer = null;

  @SerializedName("balances")
  private List<RewardBalance> balances = null;

  public RewardMembership accountIds(List<String> accountIds) {
    this.accountIds = accountIds;
    return this;
  }

  public RewardMembership addAccountIdsItem(String accountIdsItem) {
    if (this.accountIds == null) {
      this.accountIds = new ArrayList<String>();
    }
    this.accountIds.add(accountIdsItem);
    return this;
  }

   /**
   * accountIds associated to the reward program
   * @return accountIds
  **/
  @Schema(description = "accountIds associated to the reward program")
  public List<String> getAccountIds() {
    return accountIds;
  }

  public void setAccountIds(List<String> accountIds) {
    this.accountIds = accountIds;
  }

  public RewardMembership customerId(String customerId) {
    this.customerId = customerId;
    return this;
  }

   /**
   * Get customerId
   * @return customerId
  **/
  @Schema(description = "")
  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public RewardMembership memberId(String memberId) {
    this.memberId = memberId;
    return this;
  }

   /**
   * Get memberId
   * @return memberId
  **/
  @Schema(description = "")
  public String getMemberId() {
    return memberId;
  }

  public void setMemberId(String memberId) {
    this.memberId = memberId;
  }

  public RewardMembership memberNumber(String memberNumber) {
    this.memberNumber = memberNumber;
    return this;
  }

   /**
   * Reward program membership number
   * @return memberNumber
  **/
  @Schema(description = "Reward program membership number")
  public String getMemberNumber() {
    return memberNumber;
  }

  public void setMemberNumber(String memberNumber) {
    this.memberNumber = memberNumber;
  }

  public RewardMembership memberTier(String memberTier) {
    this.memberTier = memberTier;
    return this;
  }

   /**
   * If the reward program is tiered, member&#x27;s current tier
   * @return memberTier
  **/
  @Schema(description = "If the reward program is tiered, member's current tier")
  public String getMemberTier() {
    return memberTier;
  }

  public void setMemberTier(String memberTier) {
    this.memberTier = memberTier;
  }

  public RewardMembership businessOrConsumer(BusinessOrConsumer businessOrConsumer) {
    this.businessOrConsumer = businessOrConsumer;
    return this;
  }

   /**
   * Get businessOrConsumer
   * @return businessOrConsumer
  **/
  @Schema(description = "")
  public BusinessOrConsumer getBusinessOrConsumer() {
    return businessOrConsumer;
  }

  public void setBusinessOrConsumer(BusinessOrConsumer businessOrConsumer) {
    this.businessOrConsumer = businessOrConsumer;
  }

  public RewardMembership balances(List<RewardBalance> balances) {
    this.balances = balances;
    return this;
  }

  public RewardMembership addBalancesItem(RewardBalance balancesItem) {
    if (this.balances == null) {
      this.balances = new ArrayList<RewardBalance>();
    }
    this.balances.add(balancesItem);
    return this;
  }

   /**
   * Array of balances
   * @return balances
  **/
  @Schema(description = "Array of balances")
  public List<RewardBalance> getBalances() {
    return balances;
  }

  public void setBalances(List<RewardBalance> balances) {
    this.balances = balances;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RewardMembership rewardMembership = (RewardMembership) o;
    return Objects.equals(this.accountIds, rewardMembership.accountIds) &&
        Objects.equals(this.customerId, rewardMembership.customerId) &&
        Objects.equals(this.memberId, rewardMembership.memberId) &&
        Objects.equals(this.memberNumber, rewardMembership.memberNumber) &&
        Objects.equals(this.memberTier, rewardMembership.memberTier) &&
        Objects.equals(this.businessOrConsumer, rewardMembership.businessOrConsumer) &&
        Objects.equals(this.balances, rewardMembership.balances);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountIds, customerId, memberId, memberNumber, memberTier, businessOrConsumer, balances);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RewardMembership {\n");
    
    sb.append("    accountIds: ").append(toIndentedString(accountIds)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    memberId: ").append(toIndentedString(memberId)).append("\n");
    sb.append("    memberNumber: ").append(toIndentedString(memberNumber)).append("\n");
    sb.append("    memberTier: ").append(toIndentedString(memberTier)).append("\n");
    sb.append("    businessOrConsumer: ").append(toIndentedString(businessOrConsumer)).append("\n");
    sb.append("    balances: ").append(toIndentedString(balances)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
