/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.PageMetadata;
import io.swagger.client.model.PageMetadataLinks;
import io.swagger.client.model.PaginatedArray;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Optionally paginated array of transactions
 */
@Schema(description = "Optionally paginated array of transactions")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-16T18:27:34.841Z[GMT]")
public class Transactions extends PaginatedArray {
  @SerializedName("transactions")
  private List<Object> transactions = null;

  public Transactions transactions(List<Object> transactions) {
    this.transactions = transactions;
    return this;
  }

  public Transactions addTransactionsItem(Object transactionsItem) {
    if (this.transactions == null) {
      this.transactions = new ArrayList<Object>();
    }
    this.transactions.add(transactionsItem);
    return this;
  }

   /**
   * An array of transactions with entity type dependent on the account type (deposit, loan, line of credit, investment or insurance)
   * @return transactions
  **/
  @Schema(description = "An array of transactions with entity type dependent on the account type (deposit, loan, line of credit, investment or insurance)")
  public List<Object> getTransactions() {
    return transactions;
  }

  public void setTransactions(List<Object> transactions) {
    this.transactions = transactions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transactions transactions = (Transactions) o;
    return Objects.equals(this.transactions, transactions.transactions) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactions, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transactions {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
