/*
 * FDX V5.0
 * Financial Data Exchange V5.0 Core API
 *
 * OpenAPI spec version: 5.0.0
 * Contact: fdxsupport@financialdataexchange.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.swagger.client.model.RewardProgram;
import io.swagger.client.model.RewardPrograms;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class RewardProgramInformationApi {
    private ApiClient apiClient;

    public RewardProgramInformationApi() {
        this(Configuration.getDefaultApiClient());
    }

    public RewardProgramInformationApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for getRewardProgram
     * @param authorization Access token for authentication and authorization (required)
     * @param rewardProgramId Reward Program Identifier (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getRewardProgramCall(String authorization, String rewardProgramId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/reward-programs/{rewardProgramId}"
            .replaceAll("\\{" + "rewardProgramId" + "\\}", apiClient.escapeString(rewardProgramId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        if (authorization != null)
        localVarHeaderParams.put("Authorization", apiClient.parameterToString(authorization));

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getRewardProgramValidateBeforeCall(String authorization, String rewardProgramId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'authorization' is set
        if (authorization == null) {
            throw new ApiException("Missing the required parameter 'authorization' when calling getRewardProgram(Async)");
        }
        // verify the required parameter 'rewardProgramId' is set
        if (rewardProgramId == null) {
            throw new ApiException("Missing the required parameter 'rewardProgramId' when calling getRewardProgram(Async)");
        }
        
        com.squareup.okhttp.Call call = getRewardProgramCall(authorization, rewardProgramId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Get reward program
     * Get a specific reward program
     * @param authorization Access token for authentication and authorization (required)
     * @param rewardProgramId Reward Program Identifier (required)
     * @return RewardProgram
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public RewardProgram getRewardProgram(String authorization, String rewardProgramId) throws ApiException {
        ApiResponse<RewardProgram> resp = getRewardProgramWithHttpInfo(authorization, rewardProgramId);
        return resp.getData();
    }

    /**
     * Get reward program
     * Get a specific reward program
     * @param authorization Access token for authentication and authorization (required)
     * @param rewardProgramId Reward Program Identifier (required)
     * @return ApiResponse&lt;RewardProgram&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<RewardProgram> getRewardProgramWithHttpInfo(String authorization, String rewardProgramId) throws ApiException {
        com.squareup.okhttp.Call call = getRewardProgramValidateBeforeCall(authorization, rewardProgramId, null, null);
        Type localVarReturnType = new TypeToken<RewardProgram>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get reward program (asynchronously)
     * Get a specific reward program
     * @param authorization Access token for authentication and authorization (required)
     * @param rewardProgramId Reward Program Identifier (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getRewardProgramAsync(String authorization, String rewardProgramId, final ApiCallback<RewardProgram> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getRewardProgramValidateBeforeCall(authorization, rewardProgramId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<RewardProgram>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for searchRewardPrograms
     * @param authorization Access token for authentication and authorization (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call searchRewardProgramsCall(String authorization, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/reward-programs";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        if (authorization != null)
        localVarHeaderParams.put("Authorization", apiClient.parameterToString(authorization));

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call searchRewardProgramsValidateBeforeCall(String authorization, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'authorization' is set
        if (authorization == null) {
            throw new ApiException("Missing the required parameter 'authorization' when calling searchRewardPrograms(Async)");
        }
        
        com.squareup.okhttp.Call call = searchRewardProgramsCall(authorization, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Search reward programs
     * Query all reward programs
     * @param authorization Access token for authentication and authorization (required)
     * @return RewardPrograms
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public RewardPrograms searchRewardPrograms(String authorization) throws ApiException {
        ApiResponse<RewardPrograms> resp = searchRewardProgramsWithHttpInfo(authorization);
        return resp.getData();
    }

    /**
     * Search reward programs
     * Query all reward programs
     * @param authorization Access token for authentication and authorization (required)
     * @return ApiResponse&lt;RewardPrograms&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<RewardPrograms> searchRewardProgramsWithHttpInfo(String authorization) throws ApiException {
        com.squareup.okhttp.Call call = searchRewardProgramsValidateBeforeCall(authorization, null, null);
        Type localVarReturnType = new TypeToken<RewardPrograms>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Search reward programs (asynchronously)
     * Query all reward programs
     * @param authorization Access token for authentication and authorization (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call searchRewardProgramsAsync(String authorization, final ApiCallback<RewardPrograms> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = searchRewardProgramsValidateBeforeCall(authorization, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<RewardPrograms>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
